### ISSUE TITLE
为什么打开是空白的

### ISSUE THREAD

**Issue by qulong0908** [WecomTeam/RobotSample#1]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/50685016/160368800-7dfa12a0-61f3-4fd1-97e7-dbf8a01648f6.png">

**Comment by best666** [comment]
外面的项目是启动服务器，页面在项目里的vue文件夹，vscode单独打开vue文件夹安装依赖后运行就能在8080端口看到页面了

**Comment by meterscao** [comment]
机器人相关的Demo，已经合并到自建应用的 Demo中了，请前往查看 https://github.com/WecomTeam/CodeSameples
